# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0

  inputs:
    versionSpec: '18.x'


- script: |
    echo "Node Version:"
    node -v

    echo "NPM Version:"
    npm -v

    echo "Cleaning npm cache..."
    npm cache clean --force
    echo "Installing dependencies..."
    npm ci

    echo "Installed Versions:"
    npm ls next || true
    npm ls webpack || true
  displayName: 'Install Dependencies'
      
- script: |
    npm run build
  displayName: 'npm build applications'
